name: 'Pull request automerge action'
description: 'GitHub Action to automatically merge pull requests when some conditions are met'
branding:
  icon: 'git-merge'
  color: 'purple'
inputs:
  merge-method:
    description: 'Pull request merge method. One between merge, squash, rebase'
    required: false
    default: 'squash'
  min-approvals:
    description: 'Minimum numbers of approvals to merge the pull request'
    required: false
    default: 2
  base-ref:
    description: 'Base ref branch to filter pull requests'
    required: false
    default: 'dev'
runs:
  using: 'node20'
  main: 'dist/index.js'